typography_spectrum: 0.9947322092484683
color:
  brandColors:
    - '#ffffff'
    - '#191c19'
    - '#31647f'
    - '#d8b093'
    - '#704f3b'
  brandStrength: 0.5790535942651331
  lightness: 0.08491480303928256
  saturation: 0.5373824145644903
  rhythmicContrast: 0.3632951744366437
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4833
analytics:
  google: null
  facebook: null
  twitter: null
name: travisclark
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: This is a tagline
purpose: []
