name: travisclark
favicon: null
layout_spectrum: 0.4833
typography_spectrum: 0.9947322092484683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5790535942651331
  lightness: 0.08491480303928256
  saturation: 0.5373824145644903
  rhythmicContrast: 0.3632951744366437
purpose: []
